In [2]:
import numpy as np

In [209]:
#1. Create an array of 20 Zeros
array1 = np.zeros(20)
array1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [210]:
#2. Create an array of 20 Ones
array2 = np.ones(20)
array2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [211]:
#3. Create an array of 20 Fives
array3 = np.ones(20)*5
array3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [212]:
#4. Create an array of the Integer from 25 to 50
array4 = np.arange(25,51)
array4

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50])

In [224]:
#5. Create an array of the first 50 even numbers
array5 = np.arange(0,100,2)
print(array5)
print('length: ',len(array5))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
length:  50


In [228]:
#6. Create an array of the first 50 odd numbers
array6 = np.arange(1,100,2)
print(array6)
print('length: ',len(array6))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
length:  50


In [4]:
#7. Create an array of 3 X 3 matrix with the values ranging from 0 to 8
array7 = np.arange(0,9).reshape(3,3)
array7

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
#8. Create an array of 3 X 3 matrix with the values ranging from 10 to 18
array8 = np.arange(10,19).reshape(3,3)
array8

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [7]:
#9. Create an array of 3 X 3 identity matrix
array9 = np.eye(3,dtype=int)
array9

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [8]:
#10. Create an random number between 0-1
rand = np.random.random()
rand

0.36717406998889623

In [13]:
#11. Generate 25 random numbers sampled from standard normal distribution 
array11 = np.random.normal(0,1,25)
array11

array([-1.38679438, -1.03785252, -0.9697395 , -0.562851  ,  0.77680882,
       -0.12772442, -0.32377123, -0.83908443,  0.10482229, -1.24580948,
       -1.34051961,  0.82756234, -1.71004801,  1.0624779 ,  0.37781644,
        1.55625733,  0.21223587, -1.52616752, -0.98483851, -0.48652488,
        0.24884664, -0.06739269,  0.25238594,  0.95021607,  0.32948953])

In [15]:
#12. Generate 5 * 5 matrix with 25 random numbers sampled from standard normal distribution
array11 = np.random.normal(0,1,25).reshape(5,5)
array11

array([[ 1.51461185, -1.75201946, -0.08376473,  0.83787811,  1.51863787],
       [-0.81861166,  1.82648208,  0.12723786,  0.086473  ,  1.91090344],
       [-0.70272039,  1.09468164,  1.04154988, -2.38102496,  0.25497975],
       [-0.33752134,  1.20599008, -0.6666612 , -1.16613673,  0.73478621],
       [-1.25725915,  0.72571553, -1.12485903,  0.95863601, -0.03660515]])

In [17]:
#13. Create an array of 10 linearly spaced points between 0 to 1
array12 = np.linspace(0,1,10)
array12

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [38]:
'''14. Generate following output:
        [[0.1 0.2 0.3]
         [0.4 0.5 0.6]
         [0.7 0.8 0.9]]
'''
array13 = np.linspace(.1,.9,9).reshape(3,3)
array13

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [115]:
'''
15. Using the following array:
       [[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]]
  a. Print the following output:
	[[18, 19, 20],
         [23, 24, 25]]
  b. Print the following martrix:
        [[ 9, 10],
         [14, 15],
         [24, 25]]
  c. Print the following matrix:
	[[ 2],
         [ 7],
         [12]] 
  d. Print the following matrix:
	[[21, 22, 23, 24, 25]]
  e. Print the following matrix:
	[[1,3,4],[1,3,4]]

'''
#a
array14 = np.arange(1,26).reshape(5,5)
print('a: ')
print(array14[3:,2:])
#b
# print('b: ',array14[[1,2,4],[3]])
print('b: ')
print(array14[[1,2,4],3:])
#c
print('c: ')
print(array14[:3,[1]])
#d
print('d: ')
print(array14[[4]])
#e
print('e: ')
print(array14[[0],[0,2,3]])

a: 
[[18 19 20]
 [23 24 25]]
b: 
[[ 9 10]
 [14 15]
 [24 25]]
c: 
[[ 2]
 [ 7]
 [12]]
d: 
[[21 22 23 24 25]]
e: 
[1 3 4]


In [121]:
'''
16. Using the following array:
      [[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]]

    a. Find the sum of the all the elements
    b. Find the max, and min element
    c. Print the sum of each column
    d. Print the sum of each row
    e. Print the max element location
  
'''
array15 = np.arange(1,26).reshape(5,5)
#a
print('sum: ',np.sum(array15))
#b
print('max: ',np.max(array15))
print('min: ',np.min(array15))
#c
print('column sum: ',np.sum(array15,axis=0))
#d
print('row sum: ',np.sum(array15,axis=1))
#e
print('max element loc: ',np.argmax(array15))

sum:  325
max:  25
min:  1
column sum:  [55 60 65 70 75]
row sum:  [ 15  40  65  90 115]
max element loc:  24


In [3]:
'''
17. Using the following array:
      [[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]]
    
    a. Get all the even numbers
    b. Get all the prime numbers
    c. Get all the numbers, which are divisible by 5

'''
array16 = np.arange(1,26).reshape(5,5)
# print(array16)
#a
print('even numbers: ',array16[array16 % 2==0])

#b
flatAr = array16.flatten()
def isPrime(num):
    if num < 2:
        return False
    for i in range(2,num//2+1):
        if num%i == 0:
            return False
    return True

primeAr=list(filter(isPrime, flatAr))

print('prime numbers: ',primeAr)

#c
print('divisible by 5: ',array16[array16%5==0])

even numbers:  [ 2  4  6  8 10 12 14 16 18 20 22 24]
prime numbers:  [2, 3, 5, 7, 11, 13, 17, 19, 23]
divisible by 5:  [ 5 10 15 20 25]
